### ISSUE TITLE
Handle smart contract additions in the SDK.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-java-sdk#17]
**Task description**

The V1 smart contract feature adds a few things to the API of the node that need to be handled.

**Sub-tasks**
- [ ] There are two new transaction events "Resumed" and "Interrupted". The Updated and Initialized events have an additional field "contractVersion" that indicates which version of the contract was updated.
- [ ] ~~There is a new endpoint "InvokeContract"~~
- [ ] ~~The format of "GetContractInfo" has changed. It now has a version field, and V1 contracts do not return the state.~~

The latter two tasks should be part of https://github.com/Concordium/concordium-java-sdk/issues/20

The most urgent thing to address is the new events since the SDK currently does not handle smart contracts anyhow. If only one of the tasks will be addressed then the others should be split into independent tasks.
